# Generated by Django 3.2.18 on 2023-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='background_image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
