# Generated by Django 3.2.18 on 2023-03-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_aboutme_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='background_image',
            new_name='profile_image',
        ),
    ]
