# Generated by Django 3.2.18 on 2023-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20230325_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_time',
            field=models.IntegerField(),
        ),
    ]
