# Generated by Django 3.2.18 on 2023-03-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_skill_skill_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolioTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='resume.skillcategory', verbose_name='category'),
        ),
    ]
