# Generated by Django 3.2.18 on 2023-03-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20230328_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='resume.portfoliotab'),
            preserve_default=False,
        ),
    ]
